---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install Apache
    yum:  name=httpd state=present

  - name: Start Apache Service
    service: name=httpd state=started enabled=true

  - name: Create Dir to Downlaod Tomcat.
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8
    yum: name=java-1.8.0-openjdk state=present


  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"

  - name: Copy Index Page Files
    copy: src=templates/apps dest=/opt/SP/apps/tomcat/webapps/ mode=0644
    notify:
    - Restart Tomcat


  - name: Copy addressbook War Files
    copy: src=templates/addressbook.war dest=/opt/SP/apps/tomcat/webapps/ mode=0644

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start"
